/-
Copyright (c) 2025 Raphael Douglas Giles. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Raphael Douglas Giles
-/
--import Mathlib.RingTheory.KrullDimension.NonZeroDivisors
--import Mathlib.RingTheory.Length
--import Mathlib.RingTheory.HopkinsLevitzki
import Mathlib
/-!
# Order of vanishing

This file defines the order of vanishing of an element of a ring as the length of the quotient of
the ring by the ideal generated by that element. We also define the extension of this notion to the
field of fractions
-/

open LinearMap Pointwise IsLocalization Ideal WithZero

variable {R : Type*} {M : Type*} [AddCommMonoid M]


variable [CommRing R] [Module R M]


namespace Ring
variable (R)

/--
Variation of `ord_mul` where the user has to show the first input is a non
zero divisor rather than the second.
-/
lemma ord_mul' {a b : R} (ha : a ∈ nonZeroDivisors R) :
    ord R (a * b) = ord R a + ord R b := by
  rw [mul_comm, ord_mul R ha, add_comm]


variable {R} in
/--
If `x` is a non zero divisor, `ordMonoidWithZeroHom` is equal to the canonical embedding
of `Ring.ord R x` into `WithZero (Multiplicative ℤ)`.
-/
@[simp]
theorem ordMonoidWithZeroHom_eq_ord [Nontrivial R] (x : R) (h : x ∈ nonZeroDivisors R) :
    ordMonoidWithZeroHom R x =
  WithZero.map' (Nat.castAddMonoidHom ℤ).toMultiplicative (Ring.ord R x) := dif_pos h

variable {R} in
/--
If `x` is not a non zero divisor, `ordMonoidWithZeroHom` is equal to `0`.
-/
@[simp]
theorem ordMonoidWithZeroHom_eq_zero [Nontrivial R] (x : R) (h : x ∉ nonZeroDivisors R) :
    ordMonoidWithZeroHom R x = 0 := dif_neg h


end Ring
